### ISSUE TITLE
Q: Why is the API/authorization.py #51 cls Type'Model '?

### ISSUE THREAD

**Issue by SaladDay** [321CQU/API_Gateway#10]
From a semantic point of view, shouldn't it be ‘TokenPayload’

**Comment by ZhuLegend** [comment]
Initially, the `parse_obj` method was rewritten as the [corresponding method in the `BaseModel` of pydantic v1](https://docs.pydantic.dev/1.10/usage/models/#helper-functions) to directly convert the `ValidationError` to the `_321CQUException` to avoid duplicate try-catch handling of exception conversions. Therefore, this method has the same method signature as the `parse_obj` at that time. In Pydantic v2, the `parse_obj` method was deprecated and replaced with `model_validate`. When upgrading the code, I simply replaced the calling parent class method, which caused confusion about the semantics of this method.

**Comment by SaladDay** [comment]
Sorry, u seem to misunderstood me. I meant `def parse_obj(cls: Type['Model'], obj: Any) -> 'Model':`, why is the type of cls a Type['Model'], I went through the previous commits and realized that the Model class doesn't show up in the context either!

**Comment by ZhuLegend** [comment]
Because at the beginning of writing, the signature of `parse_obj` remained the same as the signature of its parent class's corresponding function. In [pydantic](https://github.com/pydantic/pydantic/blob/main/pydantic/main.py#L1093), the `cls` of `parse_obj` is type [Model].

**Comment by SaladDay** [comment]
Thanks🙏
